### ISSUE TITLE
Make audio out configurable 

### ISSUE THREAD

**Issue by gnumpi** [gnumpi/esphome_matrixio#6]
I made the audio output configurable now. @chiefymuc could you test if it is working with your speakers? I don't have any connected yet. The branch is called speaker_configuration. Thanks.

**Comment by andersonsmith** [comment]
Hey @gnumpi, I have speakers in my matrix and gave this a quick run.   Works well with manual voice triggering.  When I turn on continuous audio streaming for use with wake word, there is a constant hiss/crackle in the speaker.  When continuous streaming isturned off, there is a very quiet hiss that you have to have your ear close to in order to pick up.  Sitting idle, it will spontaneously crackle from time to time.

Audio output quality isn't great but I seem to remember this being a challenge with the Rhasspy/Hermes server configuration as well so maybe a hardware limitation.

**Comment by chiefymuc** [comment]
Seconding @andersonsmith observation. Works just fine, but there is a bit of hiss/crackle in the speaker and some crack when the audio return starts.

Btw, is it expected that the esphome-matrix speaker does not show up as one of the audio output devices in Home Assistant (to play anything from media tab, like a voice or radio for example)?

**Comment by gnumpi** [comment]
Thank you guys for testing. Regarding the hiss/crackle, probably there is not much we can do about it. I guess these are inferences from the electronic circuits. I tested muting the PAM8019 while there is no audio playing but it doesn't seem to have any effect on the noise. Maybe we can reduce that crack that occurs when audio starts though, I will look into it.

Regarding using the matrix voice as a media player in Home Assistant, it is generally possible but I haven't integrated the matrixio platform for the esphome media_player yet.

**Comment by chiefymuc** [comment]
Yeah I remember that this is probably just a bad PCB design. Maybe better off using the headphone socket after all.

I see regarding the media_player.

Thanks for all the work on this again, this is totally amazing and gives new life to this device!
